### ISSUE TITLE
magento/module-mysql-mq isn't really optional

### ISSUE THREAD

**Issue by peterjaap** [yireo/magento2-replace-core#9]
The mass "Update attributes" functionality in the product grid in the backend relies on `magento/module-mysql-mq` to function, otherwise you'll get this notice "Something went wrong while updating the product(s) attributes";

![image](https://user-images.githubusercontent.com/431360/83018071-f9e4a700-a024-11ea-9f83-881c09e528b9.png)

```
[2020-05-27 11:44:53] .CRITICAL: Exception message: Unknown connection name db
Trace: <pre>#1 Magento\Framework\MessageQueue\PublisherPool->getPublisherForConnectionNameAndType() called at [vendor/magento/framework-message-queue/PublisherPool.php:88]
#2 Magento\Framework\MessageQueue\PublisherPool->publish() called at [vendor/magento/module-asynchronous-operations/Model/BulkManagement.php:204]
#3 Magento\AsynchronousOperations\Model\BulkManagement->publishOperations() called at [vendor/magento/module-asynchronous-operations/Model/BulkManagement.php:128]
#4 Magento\AsynchronousOperations\Model\BulkManagement->scheduleBulk() called at [vendor/magento/module-catalog/Controller/Adminhtml/Product/Action/Attribute/Save.php:273]
```

... etc

**Comment by sprankhub** [comment]
I just encountered this myself. This also seems to break (at least parts) of the REST API used by the MFTF tests (`/rest/V1/integration/admin/token`).

@jissereitsma what do you think, could you make sure that `magento/module-mysql-mq` is not replaced?

@peterjaap do you know of any proper workaround for that? It is not possible to use this package if one needs one specific package from it, because it is not possible to "un-replace" a package, right?

**Comment by peterjaap** [comment]
@sprankhub we dont't actually use these `yireo/replace-*` extension at all - I just copy the list into the `composer.json` in the project and remove the modules that we do need (which is always at least one).

**Comment by jissereitsma** [comment]
To finally add my own cents to this conversation: These kinds of issues keep bugging us. Mainly, it seems hard to get to a specific subset of modules that can safely be disabled, because often still the Magento core is not documenting its dependencies correctly.

What I'm personally thinking of and actually already started building is a CI/CD system that at least uses simple `composer` and Magento commands to check for the basics. However, this would not solve the issue of the MySQL MQ module not being properly documented as a dependency. 

I've now solved this specific issue, by quickly removing the module again from this replace-package. But to me, the puzzle is more complex. Because if someone would never use the **Update attributes** button (which is apparently still using old code without proper dependency checking), things would be fine. I'm not sure where to take these replace-packages: I think they should work out of the box, but still it is impossible to cover all edge-case scenarios.

I've been also dreaming of some kind of tool that would simply generate the right `replace` rules in your local `composer.json` file, depending on some kind of questions answered via a wizard. But hey, dreams ....

**Comment by sprankhub** [comment]
> I've now solved this specific issue, by quickly removing the module again from this replace-package.

I cannot see this change. Could you double check, @jissereitsma?

**Comment by jissereitsma** [comment]
Indeed the release was not yet made (branch exists, but tag & release need to be created following from this). Now it should be updated.
